imports:
  - { resource: 'services_common.yml'}

services:
  Wizacha\ApmBundle\ApmSubscriber:
    class: Wizacha\ApmBundle\ApmSubscriber
    arguments:
      $agentService: '@elastic_apm.service.agent_service'
    tags:
      - { name: kernel.event_subscriber }
