imports:
  - { resource: 'services_common.yml'}

services:
  Wizacha\ElasticApmBundle\ElasticApmSubscriber:
    class: Wizacha\ElasticApmBundle\ElasticApmAbstractSubscriber
    arguments:
      $agentService: '@Wizacha\ElasticApm\Service\AgentService'
    tags:
      - { name: kernel.event_subscriber }
