services:
  _defaults:
    autowire: true
    autoconfigure: true

  Wizacha\ElasticApmBundle\ElasticApmSubscriber:
    class: Wizacha\ElasticApmBundle\ElasticApmSubscriber
    tags:
      - { name: kernel.event_subscriber }

  Wizacha\ElasticApm\Service\AgentService:
    autowire: true

  PhilKra\Agent:
    class: PhilKra\Agent
    arguments:
      - { appName: '%philkra.app_name%', appVersion: '%philkra.app_version%', environment: '%philkra.environment%', serverUrl: '%philkra.server_url%', secretToken: '%philkra.secret_token%' }

  Wizacha\ElasticApmBundle\DependencyInjection\ElasticApmExtension:
    class: Wizacha\ElasticApmBundle\DependencyInjection\ElasticApmExtension
    tags:
      - { name: apm_bundle.extension }
