parameters:
  philkra.app_name: '%env(PHILKRA_APP_NAME)%'
  philkra.app_version: '%env(PHILKRA_APP_VERSION)%'
  philkra.environment: '%env(PHILKRA_ENVIRONMENT)%'
  philkra.server_url: '%env(PHILKRA_SERVER_URL)%'
  philkra.secret_token: '%env(PHILKRA_SECRET_TOKEN)%'
  elastic_apm.enabled: '%env(ELASTIC_APM_ENABLED)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Wizacha\ElasticApmBundle\ElasticApmSubscriber:
    class: Wizacha\ElasticApmBundle\ElasticApmSubscriber
    tags:
      - { name: kernel.event_subscriber }

  Wizacha\ElasticApm\Service\AgentService:
    autowire: true
    arguments:
      - '%elastic_apm.enabled%'
      - '@PhilKra\Agent'

  PhilKra\Agent:
    class: PhilKra\Agent
    arguments:
      - { appName: '%philkra.app_name%', appVersion: '%philkra.app_version%', environment: '%philkra.environment%', serverUrl: '%philkra.server_url%', secretToken: '%philkra.secret_token%' }

  Wizacha\ElasticApmBundle\DependencyInjection\ElasticApmExtension:
    class: Wizacha\ElasticApmBundle\DependencyInjection\ElasticApmExtension
    tags:
      - { name: apm_bundle.extension }
