imports:
  - { resource: 'services_common.yml'}

services:
  _defaults:
    bind:
      $agentService: '@Wizacha\ElasticApm\Service\AgentService'

  Wizacha\ElasticApmBundle\ElasticApmSubscriberLegacy:
    class: Wizacha\ElasticApmBundle\ElasticApmSubscriberLegacy
    tags:
      - { name: kernel.event_subscriber }
