imports:
  - { resource: 'services_common.yml'}

services:
  _defaults:
    bind:
      $agentService: '@elastic_apm.service.agent_service'

  Wizacha\ApmBundle\ApmSubscriberLegacy:
    class: Wizacha\ApmBundle\ApmSubscriberLegacy
    tags:
      - { name: kernel.event_subscriber }
